//! Smart Pointers

mod _16_1_using_box_t_to_point_to_data_on_the_heap;
mod _16_2_treating_smart_pointers_like_regular_references_with_the_deref_trait;
mod _16_3_running_code_on_cleanup_with_the_drop_trait;
mod _16_4_rc_t_the_reference_counted_smart_pointer;
mod _16_5_refcell_t_and_the_interior_mutability_pattern;
mod _16_6_reference_cycles_can_leak_memory;