//! More About Cargo and Crates.io

mod _14_1_customizing_builds_with_release_profiles;
mod _14_2_publishing_a_crate_to_crates_io;
mod _14_3_cargo_workspaces;
mod _14_4_installing_binaries_from_crates_io_with_cargo_install;
mod _14_5_extending_cargo_with_custom_commands;
