//! An I/O Project: Building a Command Line Program


mod _12_1_accepting_command_line_arguments;
mod _12_2_reading_a_file;
mod _12_3_refactoring_to_improve_modularity_and_error_handling;
mod _12_4_developing_the_library_functionality_with_test_driven_development;
mod _12_5_working_with_environment_variables;
mod _12_6_writing_error_messages_to_standard_error_instead_of_standard_output;